name: void-cinema-subtitle-api

services:
  - name: api
    type: web
    git:
      repository: github.com/munax07/Subtitle-api
      branch: main
    build:
      build_command: npm install
      run_command: npm start
    ports:
      - port: 3000
        protocol: http
    healthchecks:
      - path: /health
        port: 3000
        type: http
        interval: 30
        timeout: 10
    scaling:
      min: 1
      max: 1
    regions:
      - was
    instance_type: free
